### ISSUE TITLE
Converting BioBERT version link

### ISSUE THREAD

**Issue by JeffT13** [dmis-lab/biobert-pytorch#10]
In the README it states "You can convert any version of BioBERT into PyTorch with this." but 'this' is a dead link. Could someone please update the reference? I would like to convert some other saved biobert models to pytorch to try out. Thanks.

**Comment by wonjininfo** [comment]
Hi, 
It seems like huggingface team updated their library. 
[This issue](https://github.com/huggingface/transformers/issues/9556) also addresses the same problem. 
According to the issue, you can find `convert_bert_original_tf_checkpoint_to_pytorch.py` from [here](https://github.com/huggingface/transformers/blob/master/src/transformers/models/bert/convert_bert_original_tf_checkpoint_to_pytorch.py).

However, we used Transformers v3.x, so I think [this link](https://github.com/huggingface/transformers/blob/v3.5.1/src/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py) suits better.
Best, 
Wonjin
