### ISSUE TITLE
Running NER

### ISSUE THREAD

**Issue by SatanuG** [dmis-lab/biobert-pytorch#31]
How can I run NER of BioBERT on raw text? How do I have to preprocess the text? Is there any particular format?

**Comment by wonjininfo** [comment]
Hi,
Thank you for your interest in our work. 
You may be interested in BERN1 or [BERN2](http://bern2.korea.ac.kr/) (with better performance and throughput), which are applications of biobert / biomedical LMs (different papers) from our research group.  
Best,
Wonjin

**Comment by SatanuG** [comment]
I am sorry, but the link is not accessible. Can you please provide an alternate link or GitHub repo? 

Best,
Satanu.

**Comment by mjeensung** [comment]
Hi @SatanuG 

[BERN2](http://bern2.korea.ac.kr/) is now accessible.
Could you try it again?

**Comment by SatanuG** [comment]
Thanks a lot for your help! I can access it now.
Best,
Satanu.
