### ISSUE TITLE
syntax error when running the bash script for cv

### ISSUE THREAD

**Issue by mmmddd98** [dmis-lab/biobert-pytorch#4]
I always get this a syntax error when i am running the run_re_10cv.sh file for the cv. 
Can somebody help me to solve this ? 

`> $ sh run_re_10cv.sh

*****  euadr  train-eval  {1..10}  Start *****

  File "run_re.py", line 50
    model_name_or_path: str = field(
                                      ^
SyntaxError: invalid syntax
*****  euadr  train-eval Done *****`

**Comment by nomoreoneday** [comment]
Hi, I'm wondering if you have solved this problem? I'm running into this error too.

**Comment by mmmddd98** [comment]
I think the problem was that i didn't specify  python to python3 in the bash file.

**Comment by Shi-intel** [comment]
> I think the problem was that i didn't specify python to python3 in the bash file.

How to specify python to python3? THX
