### ISSUE TITLE
Broken link for PyTorch conversion steps

### ISSUE THREAD

**Issue by mgavish** [dmis-lab/biobert-pytorch#6]
The link provided [here](https://github.com/dmis-lab/biobert-pytorch#models) for instructions on converting models to PyTorch is broken.  Is there any info on this at this time?

**Comment by jhyuklee** [comment]
Thanks for spotting that. The original link has been modified due to the update of Huggingface transformers. You can see here: https://github.com/huggingface/transformers/blob/v3.5.1/src/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py as well.
